spring:
  application:
    name: RegisterBackend
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:file:./db
    driverClassName: org.h2.Driver
    username: sa
    password: password
